### ISSUE TITLE
I BROKE GH-PAGES!

### ISSUE THREAD

**Issue by hello-smile6** [SpellCheckJS/SpellCheckJS.github.io#2]
@webdev03 @MystPi @ScolderCreations @Sheeptester @JaydenDev @FunctionalMetatable SOMEONE, HELP!!! It's redirecting to the wrong domain!

**Comment by MystPi** [comment]
It seems like it's working. Also, please don't randomly mention people if they aren't contributors of a repo.

**Comment by hello-smile6** [comment]
> It seems like it's working. Also, please don't randomly mention people if they aren't contributors of a repo.

I'll try clearing my browser cache.

**Comment by hello-smile6** [comment]
It's redirecting everything.

**Comment by hello-smile6** [comment]
How do I clear the Microsoft Edge Chromium browser cache?

**Comment by hello-smile6** [comment]
Never mind, figured it out. I'm such an idiot.
